services: mongodb
language: ruby
before_install:
  - gem install bundler -v '1.5.1'
  - bundle -v
before_script:
  - psql -c 'create database schnitzelpress_test;' -U postgres
  - cp -f config/schnitzelpress.travis.yml config/schnitzelpress.yml
rvm:
  - 2.1.0
script: bundle exec rspec spec
