services: mongodb
language: ruby
before_install:
  - gem install bundler -v '1.7.2'
before_script:
  - psql -c 'create database schnitzelpress_test;' -U postgres
rvm:
  - 2.1.2
script: bundle exec rspec spec
