source 'https://rubygems.org'

gem 'rack'
gem 'puma'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'activesupport', '~> 3.2.0'
gem 'mongo', '~> 1.5.2'
gem 'mongoid', '~> 2.4.0'
gem 'bson_ext'
gem 'omniauth'
gem 'omniauth-browserid'
gem 'mbj-assets'
gem 'compass'
gem 'haml'
gem 'schnitzelstyle'
gem 'slim'
gem 'slodown.py'
gem 'chronic'

group :development, :test do
  gem 'rspec'
  gem 'rspec-html-matchers'
  gem 'database_cleaner'
  gem 'factory_girl', '~> 2.6.0'
  gem 'ffaker'
  gem 'timecop'
  gem 'shotgun'
  gem 'rack-test'
  gem 'watchr'
  gem 'awesome_print'
end