source 'https://rubygems.org'

gem 'rack'
gem 'puma'
gem 'substation'
gem 'adamantium', '~> 0.2'
gem 'concord'
gem 'anima'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'omniauth'
gem 'omniauth-browserid'
gem 'mbj-assets', '~> 0.0.11'
gem 'compass'
gem 'schnitzelstyle'
gem 'slim'
gem 'slodown.py'
gem 'chronic'
gem 'multi_json'
gem 'newrelic_rpm'
gem 'encrypted_cookie'
gem 'morpher'
gem 'slugify'

group :development, :test do
  gem 'rake'
  gem 'rspec'
  gem 'capybara'
  gem 'poltergeist'
  gem 'rspec-its'
  gem 'rspec-html-matchers'
  gem 'database_cleaner'
  gem 'ffaker'
  gem 'timecop'
  gem 'shotgun'
  gem 'rack-test'
  gem 'awesome_print'
  gem 'rubocop'
end
