source 'https://rubygems.org'

gem 'rack'
gem 'puma'
gem 'activesupport'
gem 'adamantium'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'omniauth'
gem 'omniauth-browserid'
gem 'mbj-assets'
gem 'compass'
gem 'schnitzelstyle'
gem 'slim'
gem 'slodown.py'
gem 'chronic'
gem 'newrelic_rpm'
gem 'encrypted_cookie'

group :development, :test do
  gem 'rake'
  gem 'rspec'
  gem 'rspec-its'
  gem 'rspec-html-matchers'
  gem 'database_cleaner'
  gem 'ffaker'
  gem 'timecop'
  gem 'shotgun'
  gem 'rack-test'
  gem 'watchr'
  gem 'awesome_print'
  gem 'rubocop'
end
