development:
  sessions:
    default:
      uri: mongodb://localhost:27017/schnitzelpress_dev

test:
  sessions:
    default:
      uri: mongodb://localhost:27017/schnitzelpress_spec

production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        safe: true
        skip_version_check: true