development:
  uri: postgres://schnitzel_dev:schnitzel@localhost/schnitzelpress_dev

test:
  uri: postgres://schnitzel_test:schnitzel@localhost/schnitzelpress_test

production:
  uri: <%= ENV['DATABASE_URL'] %>